name: jump_squadio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  dio: ^4.0.6
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  restart_app: ^1.1.0+1
  freezed_annotation: ^2.1.0
  connectivity_plus: ^2.3.6+1
  bot_toast: ^4.0.3
  flutter_localizations:
    sdk: flutter
  internet_connection_checker: ^0.0.1+4
  flutter_svg: ^1.1.4
  get_storage: ^2.0.3
  responsive_framework: ^0.2.0
  flutter_widget_from_html: ^0.8.5

dev_dependencies: 
  flutter_lints: 2.0.1
  build_runner: ^2.2.0
  mocktail: ^0.3.0
  mockito: ^5.3.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100

